Feature/message date separator
Source-Coders/react-slack-client pull request #103
Opened 2020-12-18 23:36 UTC by BitPhoenix

NOTE: Merge #102 first
- Chat component now displays ChatItems (newly added component) which at the moment can either be a message or a date separator
- Added createChatItems function to Chat component that creates an array filled and populates it with chat items (messages and date separators at proper indexes)
- Moved components that are used in Chat component into Chat folder (organization)
- Added advancedFormat plugin to dayjs to support ordinal day formatting (1st, 2nd, 3rd, etc.)
- Added dateTimeService.diff to get the difference between two datetimes
- Added dateTimeService.isSame to determine whether the two datetimes are the same

2020-12-22 16:17 UTC, luiszaval requested changes
Looks good. Works as expected. Just update mapping keys

2020-12-22 16:17 UTC, luiszaval commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
its possible sender and content could be the same. Could make use of map() 2nd param of index to make unique keys

Same with below with chat items map

2020-12-22 16:43 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .map(message => ({ type: "message", ...message, key: message.sender + message.content}))
Nice catch! I'll avoid using index for keys cause of potential complications and use sender + sent_dt instead

https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

2020-12-22 16:44 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
Nice catch! I'll avoid using index for keys cause of potential complications and use sender + sent_dt instead

https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

2020-12-22 16:46 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
Actually gonna look into using this 

https://www.npmjs.com/package/shortid

2020-12-22 16:46 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .map(message => ({ type: "message", ...message, key: message.sender + message.content}))
Actually gonna look into using this

2020-12-22 16:46 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .map(message => ({ type: "message", ...message, key: message.sender + message.content}))
https://www.npmjs.com/package/shortid

2020-12-22 16:48 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .map(message => ({ type: "message", ...message, key: message.sender + message.content}))
Looks like shortid is deprecated, nanoid is recommended 
https://github.com/ai/nanoid/

2020-12-22 16:48 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
Looks like shortid is deprecated, nanoid is recommended 
https://github.com/ai/nanoid/

2020-12-23 01:17 UTC, BitPhoenix commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
Hmm looks like nanoid is not recommended for React https://github.com/ai/nanoid/#react

I'm gonna make it sender + sent_dt (safer than sent_dt alone since two users could send at the same datetime)

2020-12-23 01:22 UTC, BitPhoenix commented
@luiszaval Left most recent comment and updated key to sender + sent_dt

2020-12-23 15:13 UTC, luiszaval approved these changes

2020-12-23 15:14 UTC, luiszaval commented on src/components/Chat/Chat.js
> +        .reduce((acc, messageChatItem) => {
Yeah that should work

2020-12-23 15:14 UTC, merged