Feature/form validation
Source-Coders/react-slack-client pull request #104
Opened 2020-12-22 19:15 UTC by luiszaval

- import new packages Formik and Yup in order for all app forms to now handle input validation
- Formik handles all of our previously explicit state that had been moved from redux
- Yup deals with error handling
- Moved all individual modal css files to one file under custom modal
- Deleted custom form component (formik now handles)
- Combined register and login css under one file (might be a good idea to create a pages folder under which these files can live)
- Updated login and register css to match timmy's previous work on login
- Updated modals presentation to use similar aspects of slack

2020-12-23 20:09 UTC, BitPhoenix requested changes
Left first pass comments!

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Modals/InviteMembersModal/InviteMembersModal.js
> +                onHide={()=>handleInviteMembersModal(false)}
Spacing () => handle...

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Modals/OrgSettingsModal/OrgSettingsModal.js
> +                            onClick={()=>this.handleInviteMembers(true)}
Spacing () => this

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Modals/PendingInvitationsModal/PendingInvitationsModal.js
> +                onHide={()=>handlePendingInvitationsModal(false)}
Spacing () =>

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Register/Register.js
> +                    validationSchema={Yup.object({
Extract schema

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Register/Register.js
> +                    onSubmit={(values, {setSubmitting, setStatus}) =>{
Extra onSubmit

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/Register/Register.js
> +                                onClick = {()=> changeRoute({path:"/login"})}
() =>

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/UI/CustomFormInput/FormInput.module.css
> +}
Space after class name

2020-12-23 20:09 UTC, BitPhoenix commented on src/components/UI/CustomModal/CustomModal.module.css
> +}
Any classes specific to a certain modal should probably go outside of the main CustomModal.module.css

2020-12-24 01:20 UTC, luiszaval commented on src/components/Login/Login.js
> +                    })}
Yeah I know right. Super intuitive and readable

2020-12-24 01:23 UTC, luiszaval commented on src/components/Login/Login.js
> +                    validationSchema={Yup.object({
Good idea. WIll do

2020-12-24 01:28 UTC, luiszaval commented on src/components/Login/Login.js
> +import styles from "../Register/Register.module.css"
Exactly what I was thinking up in my PR comments

2020-12-24 01:57 UTC, luiszaval commented on src/components/Login/Login.js
> +            <>
its shorthand for fragment:

https://reactjs.org/docs/fragments.html

fragments are recommended over divs:

https://stackoverflow.com/questions/47761894/why-are-fragments-in-react-16-better-than-container-divs

2020-12-24 02:44 UTC, BitPhoenix commented on src/components/Login/Login.js
> +            <>
Nice! I knew about fragments but wasn't familiar with the short hand syntax. Awesome to know!

2020-12-24 16:58 UTC, luiszaval commented on src/components/Modals/CreateChannelModal/CreateChannelModal.js
> +                                        {values.isPrivate && values.privateUsers && values.privateUsers.length > 0 ? (
yep got it makes a lot more sense

2020-12-26 15:21 UTC, merged