Feature Orgs Initial Implementation
Source-Coders/react-slack-client pull request #91
Opened 2020-11-12 20:31 UTC by BitPhoenix

- Added orgs bar on the left that lets you switch between orgs
- First org is selected as default org (similar to how we select first channel as default channel)
- Current org is properly updated in redux 
- Commented out logic that updates channels and users in redux when a new org is selected (set to that org's channels and users)

2020-11-13 17:26 UTC, luiszaval requested changes
left comments

2020-11-13 18:13 UTC, luiszaval commented on src/modules/main/actions.js
> +                dispatch(actions.org.selectOrg(defaultOrg.org_id));
defaultOrg.name

2020-11-14 15:13 UTC, BitPhoenix commented on src/modules/org/actions.js
> +        const org = orgs[orgId];
@luiszaval On client I still have this in actions.js

  ```
  const orgsFetch = actionCreator(types.FETCH_ORGS);
    const fetchOrgs = () => async (dispatch) => {
        const [err, orgs] = await to(orgService.fetchOrgs());
        if (err) {
            throw new Error("Could not fetch orgs");
        }
        const orgsMap = {};
        for (let org of orgs) {
            orgsMap[org.org_id] = org;
        }
        dispatch(orgsFetch(orgsMap));
    };
```

I'll update this logic to use name right after merging in your server side branch that contains updated org fetch route

2020-11-14 15:14 UTC, BitPhoenix commented on src/services/org-service.js
>              .then(data=>data.orgs)
Awesome, thanks for pointing this out! I'll update this logic to use name right after merging in your server side branch that contains updated org fetch route

2020-11-14 15:15 UTC, BitPhoenix commented on src/components/Org/Org.js
> +        this.props.selectOrg(orgId);
Awesome, thanks for pointing this out! I'll update this logic to use name right after merging in your server side branch that contains updated org fetch route

2020-11-14 15:15 UTC, BitPhoenix commented on src/components/Orgs/Orgs.js
> +                <Org org={org} key={org.name}  />
Awesome, thanks for pointing this out! I'll update this logic to use name right after merging in your server side branch that contains updated org fetch route

2020-11-14 15:15 UTC, BitPhoenix commented on src/modules/main/actions.js
> +                dispatch(actions.org.selectOrg(defaultOrg.org_id));
Awesome, thanks for pointing this out! I'll update this logic to use name right after merging in your server side branch that contains updated org fetch route

2020-11-18 15:15 UTC, luiszaval reviewed
Looks good to me. We can probably delete all the fetchChannels and fetchUsernames logic.

2020-11-18 15:38 UTC, luiszaval commented on src/modules/org/actions.js
> +        dispatch(orgSelect(org));
this would be better stored as a user object so we don't lose the logged_in data

2020-11-18 15:41 UTC, luiszaval commented on src/components/SideBar/SideBar.js
>                      <div className="org-name">
just putting it here as a reminder. On this file for usernames display we would just have to update code to map through user.username if we are to store it as an object in redux

2020-11-18 15:42 UTC, luiszaval commented on src/modules/user/actions.js
> +			dispatch(actions.user.fetchUsernames()), // TODO: REMOVE THIS when Luis' code ready
can delete this code

2020-11-18 18:03 UTC, BitPhoenix commented on src/modules/org/actions.js
> +        dispatch(orgSelect(org));
Yep! I didn't do it here because I figured the redux refactor to user object to include logged in status would be something probably done in the logged in status PR - was just focused on getting orgs working with existing features

2020-11-18 18:04 UTC, BitPhoenix commented on src/components/SideBar/SideBar.js
>                      <div className="org-name">
Yep! I didn't do it here because I figured the redux refactor to user object to include logged in status would be something probably done in the logged in status PR - was just focused on getting orgs working with existing features

2020-11-18 18:14 UTC, BitPhoenix commented on src/modules/user/actions.js
> +			dispatch(actions.user.fetchUsernames()), // TODO: REMOVE THIS when Luis' code ready
Good catch! Done!

2020-11-18 18:14 UTC, BitPhoenix commented
> Looks good to me. We can probably delete all the fetchChannels and fetchUsernames logic.

Good catch! Done!

2020-11-19 14:43 UTC, merged