Week 6 login status
Source-Coders/react-slack-client pull request #92
Opened 2020-11-19 18:31 UTC by luiszaval

- Added CSS for login button
- Added conditional CSS => if user is logged in
- Updated all code dependent on state.user.usernames => state.user.users
- Added a updateUsers action which is triggered on a new user joining or leaving socket events

2020-11-20 19:49 UTC, BitPhoenix requested changes
Round 1: Left comments!

2020-11-20 19:49 UTC, BitPhoenix commented on src/components/SideBar/SideBar.js
> +                        <div className={`login-circle ${user.logged_in ? "logged-in" : null}`}></div>
Nice!!!

2020-11-20 19:49 UTC, BitPhoenix commented on src/modules/chat/actions.js
> +        const usernames = Object.keys(getState().user.users);
Nice! Great job removing the for loop and just using Object.keys!

2020-11-20 19:49 UTC, BitPhoenix commented on src/modules/user/actions.js
> +        }
To continue in spirit of reducing the for loops:

`const usersMap = Object.fromEntries(users.map(user => [user.username, user]));`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

2020-11-20 19:49 UTC, BitPhoenix commented on src/modules/user/actions.js
> +	const updateUsers = (usernameToBeUpdated) => (dispatch, getState) => {
Just need a little bit more descriptive name here for function name, something to reflect that we're marking user offline.

Perhaps it should be made more generic though, and allow for setting online/offline

`updateLoggedInStatus(username, loggedIn) `

Where true is passed in to to mark online, and false to offline

2020-11-20 19:49 UTC, BitPhoenix commented on src/modules/user/actions.js
> +		dispatch(usersUpdate(updatedUsers))
```
const user = {...users.find(user => user.username === userNameToBeUpdated)};   // finds user and creates shallow copy 
user.logged_in = !user.logged_in
```

2020-11-20 19:49 UTC, BitPhoenix commented on src/store.js
> +    const middleware = applyMiddleware(thunkMiddleware, logger);
Did we have this backwards before?

2020-11-23 17:22 UTC, luiszaval commented on src/store.js
> +    const middleware = applyMiddleware(thunkMiddleware, logger);
Yeah actually. By putting it first the logger was logging both promises (all those undefined actions) and actual actions thus why our console was so clogged up. Now it should only log actions

2020-11-23 21:43 UTC, BitPhoenix requested changes
Left round 2 comment!

2020-11-23 21:43 UTC, BitPhoenix commented on src/modules/user/actions.js
> +		const updatedUsers = Object.fromEntries(Object.entries(users).map(([ username, user ]) => (
Found this a little bit hard to follow, had to pause and think a lot and I think it's because of the way the update is currently being handled with map and ternary operator. I think there's a little easier way to do the update that takes less time to digest, and it also might be better to separate it out from the fromEntries / entries calls to reduce the logic chain length and make it easier to grasp in a couple of seconds what's going on 

If we're trying to update one user, can do something like this:

```
const users = {...getState().user.users}; // copy the users object  *see below*
const user = users.values().find(user => user.name === username); // find the user to update
user.logged_in = !user.logged_in; // update property on the user
dispatch(usersUpdate(users)); 
```

The only thing that has to be tweaked about this is the first line. We need a way to create a deep copy because our users object is a complex object (is a map that contains references to other user objects). One way around this is adding lodash library to the project which has simple deepclone method

https://stackoverflow.com/a/46556129

2020-12-02 17:02 UTC, merged