Orgs Refactor
Source-Coders/react-slack-client pull request #93
Opened 2020-11-29 03:33 UTC by BitPhoenix

- Added lodash-es for deep copying objects
- Created deleteChannel action for SideBar component to call rather than calling the service method directly
- Updated channels map in Sidebar component to loop over values instead of entries 
- Updated channel_id references --> name in Sidebar component 
- Added addedToChannel action which adds a channel to the org in redux 
- Added removeChannel action which removes a channel from the org in redux
- Added setOrgs action
- deleteChannel service method now sending org_name, channel_name to backend instead of channel_id
- "channel-deleted" socket event listener updated to receive an info object containing org_name, channel_name instead of channel_id. channelDeleted action is dispatched
- "added-to-channel" socket event listener updated to receive an info object containing org_name, channel_name instead of channel_id. addedToChannel action is dispatched and "join-channel" with orgName, channelName is sent to server
---------
- Added lodash for access to lodash/fp/set (used to clean up our reducers)
- Refactored Chat component to no longer use channel_id, and updated message mapping in line with redux refactor
- Message now contains org_name 
- Created sendMessage action 
- Refactored addedToChannel action to simply dispatch  
- Created sidebar.selectDefaultChannel() action
- fetchNumberOfMembers method and route updated to accept orgName (now a post route as well)
- Commented out all init message related actions / reducer code (have to see if it's still necessary)
- Removed workspace redux module (redudant because we have org module)
- Created org.selectDefaultOrg() action
- Updated message actions to user orgName and channelName 
- fetchChannelMessages method and route updated to accept orgName (now a post route as well)
- fetchPrivateMessages method and route updated to accept orgName (now a post route as well)
- added setChannelMessages and setPrivateMessages actions
- message reducer updated for new state structure (now have multiple orgs)
- Refactored permissions actions and reducer to work using orgName and channelName rather than id's 
- Sidebar actions updated to use channelName rather than id
---------
- Added optional chaining for accessing messages in a given org 
- Updated state mapping of channels property in Sidebar component
- Added setOrgChannels action and reducer  
---------
- Now fetching all the org channels a user is a part of
- Permissions protected the delete channel button 
- Removed fetching number of users in a channel as an action, now reading the length of the members array on each channel 
- Added optional chaining operator to messages mapping in chat component to prevent undefined errors
- Removed number of users from private chat header
- Added fetch channels action for fetching all of the channels in the org that the user is a part of 
- Fixed small bugs regarding reading fields off of objects (had the wrong name in a couple of places)
- Removed onMessageReceived from chat-service, now just dispatching the action directly from socket-service
------------
- Updated setChannels action to take in orgName and channels map
- Updated removeChannel action. Have access to an object rather than array so removed filtering and instead deleting property corresponding to that channel with delete keyword. 
------------
- Added reducers for log out action to properly clear out state
- Added extra undefined checks for case where user has no org 
- Added extra undefined check for case when orgs are set slightly before current org is selected 
- Invitations modal now calls respondToInvitation action directly
- Prevented reload in invitations modal by doing event.preventDefault()
- Removed user.usernames and from redux along with action
- Sidebar now loops over state.org.orgs[orgName].members which is a map or username to org member object containing logged in status
- Added fetchOrg and setOrg actions
- Added addedToOrg action that is called when server socket event "added-to-org" is received. Adds the org to the orgs map and in the event that it's the only org the user has, fetches the org and selects it
- Added addOrgMember action that is called whenever we receive "new-org-member" socket event which adds the org member to the members map on the org
- Added setOrgMemberOnlineStatus to allow us to update the org member value in the org.members map to reflect online/offline
- Added the following socket event listeners: "added-to-org", "added-to-org", "org-member-online", "org-member-offline"
-----------
- Now calling createOrg action instead of service in CreateOrg component
- Now sending actual current org value on invite instead of hardcoded "Source Coders"
- Added a CTA to create an org if the user has no orgs 
- Removed unneeded actions / state from Org component. Now just takes in a name
- Added create new org button to orgs selector
- Added button to orgs selector for opening org invites modal
- Org invites moved out of sidebar and into orgs selector component
- Create org modal moved out of sidebar and into orgs selector component
- Updated selectOrg action to fetch the org if we don't have the org details
- Sending "join-org" event to socket server on "added-to-channel"

2020-12-01 20:35 UTC, luiszaval commented on src/components/SideBar/SideBar.js
> +                : (Object.entries(orgMembers).map(([username, orgMember]) =>
can probably do the same as above with channels 
`
Object.values(orgMembers)
`

2020-12-01 23:54 UTC, luiszaval commented on src/modules/channel/actions.js
> +            throw new Error("Could not fetch num channel members");
update error message, maybe "could not delete channel"

2020-12-02 00:30 UTC, luiszaval commented on src/modules/org/actions.js
> +    }
Don't see this called throughout the app. Not sure if i'm missing something or its code for later use. Looks to me like most of the single org actions are taken cared of by the selectOrg action. Only instance of setOrg being used is added-to-org action below

2020-12-02 00:39 UTC, luiszaval commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
if other orgs exist we still need to make the API call for the new org info in order to populate our orgs redux with the pertinent info. See the setOrg action which accepts orgName and org

2020-12-02 01:21 UTC, luiszaval commented on src/components/MainComponent/MainComponent.js
> +import { faCaretDown, faLongArrowAltLeft, faArrowLeft } from "@fortawesome/free-solid-svg-icons";
can delete faCaretDown, faLongArrowAltLeft && canView component from line 6

2020-12-02 01:21 UTC, luiszaval commented on src/components/MainComponent/MainComponent.js
> +        const { isInitialized, orgsExist, orgs } = this.props
can delete orgsExist

2020-12-02 01:40 UTC, luiszaval commented on src/modules/invitation/actions.js
> +    const respondToInvitation = (invitation, isAccepted) => async (dispatch, getState) => {
can delete getState param

2020-12-02 01:43 UTC, BitPhoenix commented on src/modules/channel/actions.js
> +            throw new Error("Could not fetch num channel members");
Nice catch

2020-12-02 01:51 UTC, BitPhoenix commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
When you've been added to an org, the org name is added to redux which will make it display on the orgs selector.
I purposefully omitted the fetch, as I think it makes sense to only fetch the org info if they actually click into that org during the session

2020-12-02 01:51 UTC, BitPhoenix commented on src/components/MainComponent/MainComponent.js
> +import { faCaretDown, faLongArrowAltLeft, faArrowLeft } from "@fortawesome/free-solid-svg-icons";
Nice catch

2020-12-02 01:52 UTC, BitPhoenix commented on src/components/MainComponent/MainComponent.js
> +        const { isInitialized, orgsExist, orgs } = this.props
Nice catch

2020-12-02 01:53 UTC, BitPhoenix commented on src/modules/invitation/actions.js
> +    const respondToInvitation = (invitation, isAccepted) => async (dispatch, getState) => {
Nice catch

2020-12-02 01:55 UTC, luiszaval commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
ahh and so if this org is then selected and we dont have the info then we handle that in the select-org action. Just figured since our redux org is populated with all of the orgs information that we would want to do that here. But it makes sense

2020-12-02 02:02 UTC, BitPhoenix commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
One thing I'll update here is removing the fetch in the else case, because it's covered in selectOrg

2020-12-02 02:09 UTC, luiszaval commented on src/components/Org/Org.js
> +export default Org;
we could probably just make this a functional component

2020-12-02 02:12 UTC, luiszaval commented on src/components/Orgs/Orgs.js
>  class Orgs extends Component {
maybe we can rename component OrgsSidebar for differentiation with org?

2020-12-02 02:17 UTC, luiszaval commented on src/modules/message/actions.js
> +import { actions } from "../../context";
can delete

2020-12-02 02:23 UTC, luiszaval commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
makes sense

2020-12-02 02:27 UTC, luiszaval requested changes
Impressive stuff as always!! couple of very minor considerations

2020-12-02 14:22 UTC, BitPhoenix commented on src/modules/org/actions.js
> +            dispatch(selectDefaultOrg());
Yep exactly!

Just figured since our redux org is populated with all of the orgs information that we would want to do that here. But it makes sense"

Yep your reasoning totally makes sense! I did it this way to be in line with the small refactoring we talked about that we wanted to do in the future, to only fetch names of orgs in the beginning (and then select default first org) rather than fetching all org info in login bundle (even if user will never click into those orgs). Will be a really quick update to make in the future now that everything else is in place!

2020-12-02 14:23 UTC, BitPhoenix commented on src/components/Org/Org.js
> +export default Org;
Great idea!

2020-12-02 14:28 UTC, BitPhoenix commented on src/components/Orgs/Orgs.js
>  class Orgs extends Component {
Totally agree!

2020-12-02 14:29 UTC, BitPhoenix commented on src/modules/message/actions.js
> +import { actions } from "../../context";
Nice catch

2020-12-02 15:41 UTC, BitPhoenix commented
Addressed comments and pushed!

2020-12-02 15:41 UTC, merged