Fetch previous messages and message date time fixes / improvements
Source-Coders/react-slack-client pull request #97
Opened 2020-12-12 22:20 UTC by BitPhoenix

- Added dayjs to project (great library for working with dates / times)
- Now only showing h:mm PM/AM format in message component (in anticipation of having date separators like slack does (see rs_todo))
- Added fetchPreviousMessages function to chat component which will fetch the 25 messages most recent previous messages (works by sending over the sent_dt field of the oldest available message to the server to use in query)
- Right now this function is called on a button click but Timmy is going to have it execute on scroll up
- Created dateTimeService for getting the current date time as a string and for converting a date time string to a datetime (using dayjs instances)
- Updated message-service fetchChannelMessages and fetchPrivateMessages to accept optional parameter beforeDateTime. If provided, it will be sent over to the server in the request body and the server will use it in the query to fetch 25 most recent messages before that datetime

2020-12-13 22:55 UTC, luiszaval requested changes
Looks good!

Just a couple of things that may just come down to my lack of knowledge of new package

2020-12-13 22:55 UTC, luiszaval commented on src/components/Message/Message.js
> +    const sentDt = services.dateTimeService.dt(props.sent_dt).format("h:mm A")
could maybe do services.dateTimeService.formatForDisplay(props.send_dt)
& create the formatForDisplay (or whatever function name) function in dateTimeService since .format() is a method of dayjs. Not necessary but would keep all the dayjs functionality in dateTimeService

Could also destructure send_dt 
```
function Message({send_dt}) {
```

2020-12-13 22:55 UTC, luiszaval commented on src/services/chat-service.js
> +        const sentDt = dateTimeService.getDtStr();
not 100% sure but looks like line 11 is being handled by line 12 when we call dayjs() in datetime-service

2020-12-13 22:55 UTC, luiszaval commented on src/services/chat-service.js
> +const dayjs = require("dayjs");
was looking through the docs but did not see if this is here in order to maintain formatting? Else it looks like all dayjs functionality is handled in datetime-service and this can be deleted

2020-12-14 15:31 UTC, BitPhoenix commented on src/components/Message/Message.js
> +    const sentDt = services.dateTimeService.dt(props.sent_dt).format("h:mm A")
Will update the sent_dt destructuring ✔️!

I can't quite do services.dateTimeService.formatForDisplay(props.send_dt) since we would want the flexibility to format date times for display in different ways depending on where it's being used, but I like like the idea of keeping dayjs functionality in the dateTimeService ✔️. 

I'll create dateTimeService.format(dateTime, format) where format is a string representing the format (retains flexibility to format a datetime in different ways throughout the app )

2020-12-14 15:32 UTC, BitPhoenix commented on src/services/chat-service.js
> +        const sentDt = dateTimeService.getDtStr();
Nice catch! This was accidentally left over from previous way of formatting date, will delete

2020-12-14 15:33 UTC, BitPhoenix commented on src/services/chat-service.js
> +const dayjs = require("dayjs");
Yep also good catch, was accidentally left over from my initial implementation before I extracted into datetime-service. Will remove

2020-12-14 16:03 UTC, BitPhoenix commented
Added new commit based on PR comments:
- removed FORMAT from datetime-service
- removed dateTimeService.getDtStr()
- added MESSAGE_DT_FORMAT to chat-service
- added DISPLAY_MESSAGE_DT_FORMAT to message component and getting RAW_MESSAGE_DT_FORMAT from services.chatService.MESSAGE_DT_FORMAT
- now destructuring props object in Message component
- Removed unnecessary dayjs import in chat-service
- Added dateTimeService.now() to return dateTime
- Added dateTimeService.str() to convert a dateTime to a string

2020-12-14 16:05 UTC, BitPhoenix commented on src/components/Message/Message.js
> +    const sentDt = services.dateTimeService.dt(props.sent_dt).format("h:mm A")
Note: ended up naming this dateTimeService.str(dateTime, formatStr)

2020-12-14 16:11 UTC, luiszaval approved these changes

2020-12-14 16:12 UTC, merged