Component/modal refactor
Source-Coders/react-slack-client pull request #99
Opened 2020-12-13 18:21 UTC by luiszaval

- Delete Org
-- Handled in Org Settings Modal
-- **Added all pertinent redux actions** (Main feature / functionality update)

- In chat headers
-- Made html button tags used for display into div tags
-- Took into consideration plurality of members
-- Converted css => module.css

- Modals
-- NEW folder to store all Modals
-- Converted all modal CSS => module.css
-- Made use of custom UI component throughout all modals wherever possible
-- CreateChannel => CreateChannelModal
-- InvitationsModal => PendingInvitationsModal
-- InviteModal => InviteMembersModal
-- CreateOrg => CreateOrgModal
-- NEW OrgSettingsModal

- UI
-- NEW folder to store common UI elements
-- Converted all modal CSS => module.css
-- CustomForm
-- CustomButton
-- CustomFormInput
-- CustomModal
-- Did not focus on CSS ( @timmy224 will probably want to put in his styling)

- In Main Component
-- Deleted surrounding divs for orgs-sidebar, sidebar, and chat (not being handled at individual level)
-- Removed orgs-sidebar from main-wrapper, made it sticky to left of app and sizing non conditional
-- Deleted grid rows, rows are now being taken cared of at the individual component level
-- Main-wrapper only handles sidebar and chat now

- Org Settings Modal
-- Wrapped whole modal in CanView for all org members except for tadpoles
-- Wrapped delete org button in CanView for only org admin access

- In Sidebar
-- Added alert-pending CSS for when a user has outstanding org invitations

- Throughout App
-- update all references to modals to new names

- In App sidebar
-- updated CSS to handle username text overflow
-- Adjusted icon CSS

- Bootstrap classes
-- Unable to be handled by react modules, put into index.css file for now (might be a good idea to have a bootstrap dedicated css file for when we want to modify inherent bootstrap classes)

- TODO
-- Handle org name taken
-- move component specific state out of redux
-- Update custom modal handle uniform attributes and unique children

2020-12-13 20:04 UTC, BitPhoenix requested changes

2020-12-13 20:04 UTC, BitPhoenix commented on src/services/org-service.js
> +    const deleteOrg = org_name => {
orgName

2020-12-13 20:04 UTC, BitPhoenix commented on src/services/org-service.js
> +            body: JSON.stringify(org_name),
`body: JSON.stringify({org_name: orgName})`

2020-12-13 21:47 UTC, luiszaval commented on src/components/ChatHeader/ChannelChatHeader.js
> +		<div className={ chatHeader }>
Done. Think I got all instances of it

2020-12-13 21:47 UTC, luiszaval commented on src/components/Modals/CreateOrgModal/CreateOrgModal.js
> +        const form =
Done

2020-12-13 21:47 UTC, luiszaval commented on src/components/OrgsSidebar/OrgsSidebar.js
> +                    <div className="org-settings pending-invitations">
Yep good catch removed extra div

2020-12-13 21:48 UTC, luiszaval commented on src/components/OrgsSidebar/OrgsSidebar.js
> +        const alertPendingInvitations = invitations.length ?
Done

2020-12-13 21:52 UTC, luiszaval commented on src/modules/org/actions.js
> +    }
The way it's set up now is that it's always going to be currently selected org. You only get the option on current org, I think set up makes the most sense instead of displaying org options to the user, of orgs he is an admin of and selecting which one to delete or having the user input the org name.

So i only check for other orgs, if theres none then the CTA should appear

2020-12-13 21:59 UTC, luiszaval commented on src/services/org-service.js
> +            body: JSON.stringify(org_name),
server currently is expecting just a value, should I update to expect an object?

2020-12-13 22:24 UTC, BitPhoenix commented on src/modules/org/actions.js
> +    }
"The way it's set up now is that it's always going to be currently selected org"

That's true for the user that's deleting the org, but won't always be true for all other members of the org. 
Ex: This action will be called if you delete "Source Coders" while I'm viewing "Bit Buddies" 

server --> "org-deleted" socketio event --> actions.org.handleOrgDeleted(orgName)

Gonna revise my recommendation a bit to improve it: 

### removeOrg action 
Should be responsible for the following 3 things
- remove org off of orgs (it's doing that at the moment)
- check if removed org was the currently selected org. if so:
         - dispatch(setOrg(null))
         - dispatch(selectDefaultOrg())

handleOrgDeleted can be deleted with removeOrg action being called in it's place

2020-12-13 22:30 UTC, BitPhoenix commented on src/services/org-service.js
> +            body: JSON.stringify(org_name),
Ooo gotcha, that threw me off, so used to seeing us stringify a data object we send over. Seems like it's an object everywhere else and this was the one place it was not 

![image](https://user-images.githubusercontent.com/46142503/102025855-a17aba00-3d68-11eb-9a9b-d1dbbbfcee88.png)

I think it might be worth updating for consistency's sake

2020-12-13 22:40 UTC, BitPhoenix commented on src/modules/org/actions.js
> +    }
Most up to date recommendation (based on seeing what I did for channelDeleted / removeChannel actions)

const handleOrgDeleted = (orgName) => (dispatch) => {
	dispatch(removeOrg(orgName));
	const isCurrentOrgDeleted = getState().org.org?.name === orgName;
        if (isCurrentOrgDeleted) {
              dispatch(setOrg(null));
              dispatch(selectDefaultOrg())
        }
};

Basically an exact mimic of channelDeleted / removeChannel actions

2020-12-14 03:38 UTC, luiszaval commented on src/services/org-service.js
> +            body: JSON.stringify(org_name),
Yep makes sense

2020-12-14 16:44 UTC, merged